name: web-toolbox
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn
      - sqlalchemy
      - aiosqlite
      - pyjwt
      - passlib[bcrypt]
      - python-multipart
      - pydantic-settings
